name: python

on:
  push:
    branches:
      - 'add_some_basic_settings'

jobs:
  python:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
          architecture: x64
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install flake8
        run: pip install flake8
      - name: Install mypy
        run: pip install mypy
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'python'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ always() }}
      - name: Run mypy
        uses: sasanquaneuf/mypy-github-action@releases/v1
        with:
          checkName: 'python'   # NOTE: this needs to be the same as the job name
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ always() }}
      - name: Run pytest
        run: cd web; pytest .
        env:
          ATHENA_AWS_ACCESS_KEY_ID: ${{ secrets.ATHENA_AWS_ACCESS_KEY_ID }}
          ATHENA_AWS_SECRET_ACCESS_KEY: ${{ secrets.ATHENA_AWS_SECRET_ACCESS_KEY }}
          ATHENA_DATABASE: ${{ secrets.ATHENA_DATABASE }}
          LOG_TABLE_PREFIX: ${{ secrets.LOG_TABLE_PREFIX }}
          S3_LOG_BUCKET: ${{ secrets.S3_LOG_BUCKET }}
          S3_RESULT_BUCKET: ${{ secrets.S3_RESULT_BUCKET }}
          S3_RESULT_FOLDER: ${{ secrets.S3_RESULT_FOLDER }}
          ATHENA_SQS_URL: ${{ secrets.ATHENA_SQS_URL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
        if: ${{ always() }}
